site_name: SerpentariumCore
theme:
  name: material
  features:
    - content.code.copy

plugins:
- search
- mkdocstrings  

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - mkautodoc
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
