site_name: SerpentariumCore
site_url: https://weholt.github.io/serpentariumcore/
repo_url: https://github.com/weholt/serpentariumcore/
docs_dir: src/docs
site_dir: docs

nav:
- Serpentarium Core: index.md
- Coverage report: coverage.md


theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

plugins:
- search
- mkdocstrings
- coverage:
    page_name: coverage  # default
    html_report_dir: htmlcov  # defaul

extra_css:
  - style.css

markdown_extensions:
  - admonition
  - mkautodoc
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
